ALTER TABLE MEMBER DROP CONSTRAINT MB_BLOOD1_CK;
ALTER TABLE MEMBER DROP CONSTRAINT MB_BLOOD2_CK;
ALTER TABLE MEMBER ADD CONSTRAINT MB_BLOOD1_CK CHECK (blood1 IN ('A','B','O','AB','¸ð¸§'));
ALTER TABLE MEMBER ADD CONSTRAINT MB_BLOOD2_CK CHECK (blood2 IN ('RH+','RH-','¸ð¸§'));

ALTER TABLE MEMBER DROP CONSTRAINT MB_SOS_NN;

ALTER TABLE MEMBER ADD rel VARCHAR2(5 CHAR);

ALTER TABLE MEMBER ADD addmsg VARCHAR2(50 CHAR) DEFAULT '없음';
