ALTER TABLE MEMBER DROP CONSTRAINT MB_BLOOD1_CK;
ALTER TABLE MEMBER DROP CONSTRAINT MB_BLOOD2_CK;
ALTER TABLE MEMBER ADD CONSTRAINT MB_BLOOD1_CK CHECK (blood1 IN ('A','B','O','AB','모름'));
ALTER TABLE MEMBER ADD CONSTRAINT MB_BLOOD2_CK CHECK (blood2 IN ('RH+','RH-','모름'));

ALTER TABLE MEMBER DROP CONSTRAINT MB_SOS_NN;

ALTER TABLE MEMBER ADD rel VARCHAR2(5 CHAR);

